Feature/nlrfim 41
digst/OIOIDWS.Java pull request #10
Opened 2021-02-15 07:41 UTC by sihpe

- New MOCES certificate for Signature app and integrationtests
- Bootstrap scenario integrationtests Java -> Java and Java -> .Net

2021-02-15 08:18 UTC, mdbech requested changes

2021-02-15 08:18 UTC, mdbech commented on integrationtest/bootstrap/src/test/java/soap/BootstrapIntegrationTest.java
> +        driver.findElement(By.xpath("//a[@href='call_service.jsp']")).click();
Skal vi ikke have omskrevet dette scenarie, så det opføre sig som TestBootstrapScenario_IntTest?

2021-02-15 08:21 UTC, sihpe commented on integrationtest/bootstrap/src/test/java/soap/BootstrapIntegrationTest.java
> +        driver.findElement(By.xpath("//a[@href='call_service.jsp']")).click();
Som jeg forstod Morten Bødskov, så er ideen at testen imod DevTest4 skal virke helt automatiseret med Test Login / MitID simulator login og derfor ikke kræve at vi manuelt indtaster et password.

2021-02-15 17:22 UTC, mdbech commented on integrationtest/bootstrap/src/test/java/soap/BootstrapIntegrationTest.java
> +        driver.findElement(By.xpath("//a[@href='call_service.jsp']")).click();
Men her trykker man på knappen og læser ikke BST ind og benytter, som testen nedenfor.

2021-02-16 07:11 UTC, sihpe commented on integrationtest/bootstrap/src/test/java/soap/BootstrapIntegrationTest.java
> +        driver.findElement(By.xpath("//a[@href='call_service.jsp']")).click();
Ah, nu er jeg med :-)

2021-02-16 08:06 UTC, mdbech approved these changes

2021-02-16 08:07 UTC, merged